### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by rrydbirk** [10XGenomics/scHLAcount#11]
I've successfully run 31 samples, but the last one crashes. Can you tell me what's wrong? All samples have been treated the same way.

name = 'sc_hla_count'
operating_system = 'unix:Ubuntu'
crate_version = '0.1.0'
explanation = '''
Cause: assertion failed: self.len() - pos >= K::k(). Panic occurred in file '/home/travis/.c$
'''
method = 'Panic'
backtrace = '''
stack backtrace:
   0: backtrace::backtrace::libunwind::trace::haf40a01432d42c61 (0x562018522ce7)
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3$
      backtrace::backtrace::trace_unsynchronized::h86bb21cca35f9927
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3$
      backtrace::backtrace::trace::h53026d916847a4e2
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3$
   1: backtrace::capture::Backtrace::create::h15ee241c08d3314e (0x562018522243)
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3$
      backtrace::capture::Backtrace::new::hfa537f24b00fbd81
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3$
   2: human_panic::report::Report::new::hdcc2fe1769a7e55b (0x5620185111d7)
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/human-panic-1.0$
   3: human_panic::handle_dump::h319213eee1e267f2 (0x5620185108c7)
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/human-panic-1.0$
   4: sc_hla_count::main::{{closure}}::h93cf456556fa5fbd (0x562018459179)
             at /home/travis/build/10XGenomics/scHLAcount/<::human_panic::setup_panic macros$
   5: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x562018648ec9)
             at src/libstd/panicking.rs:481
   6: std::panicking::begin_panic::h51328ca360700b9a (0x5620184a3615)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   7: <debruijn::dna_string::DnaString as debruijn::Vmer>::get_kmer::h1b9ad17a9842b113 (0x56$
             at /home/travis/build/10XGenomics/scHLAcount/<::std::macros::panic macros>:4
   8: debruijn_mapping::pseudoaligner::Pseudoaligner<K>::map_read::{{closure}}::h155fc7e3bad$
             at /home/travis/.cargo/git/checkouts/rust-pseudoaligner-435331298a1cadf6/ae4aad$
   9: debruijn_mapping::pseudoaligner::Pseudoaligner<K>::map_read::hd33cd425a0e12f0a (0x5620$
             at /home/travis/.cargo/git/checkouts/rust-pseudoaligner-435331298a1cadf6/ae4aad$
  10: sc_hla_count::mapping::mapping_wrapper::h8e687a93e926ae64 (0x562018425bd2)
             at src/mapping.rs:336
  11: sc_hla_count::_main::h623a028a6a6d278a (0x56201845ee13)
             at src/main.rs:198
  12: sc_hla_count::main::h9607481a7611a730 (0x562018458fd3)
             at src/main.rs:139
  13: std::rt::lang_start::{{closure}}::h194d0e8b51bf9c2b (0x56201844fb03)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}::h447d8812e3ee306d (0x5620186487e3)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h4a61cb372364c745
             at src/libstd/panicking.rs:296
  15: __rust_maybe_catch_panic (0x56201864fd6a)
             at src/libpanic_unwind/lib.rs:82
  16: std::panicking::try::hdf71f938885bca42 (0x5620186493ad)
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind::h7e85dbf162b1611a
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h1e06cc26b9fc25ea
             at src/libstd/rt.rs:48
  17: main (0x5620184607d8)
  18: __libc_start_main (0x7f694b32ab97)
  19: _start (0x56201840c7b9)
  20: <unknown> (0x0)'''

**Comment by cdarby** [comment]
From the traceback, the error is occurring in the external code we call for read pseudoalignment. It fails to extract a substring of a read (kmer). I can't tell exactly what the issue is without knowing what read in your dataset caused the error. But based on the error, I have one guess of what could be going wrong. Among the reads scHLAcount uses for input (reads aligned to the HLA region), are there any reads that are very short (less than 20 bases, which is the kmer length used in the pseudoalignment algorithm)?

**Comment by rrydbirk** [comment]
Hi @cdarby, thanks for getting back to me. It's very likely that a short read is causing the error, I really just wanted to make sure I didn't do something wrong. Have a nice day
