### ISSUE TITLE
Run error: Segmentation fault

### ISSUE THREAD

**Issue by slukowski** [10XGenomics/scHLAcount#21]
Hi
I'm trying to run scHLAcount using 5' GEX data as outlined in the Case 2 scenario. However, I receive an error almost immediately (below), and am having trouble working out the problem:
```
10:36:38 [INFO] Created output directory at results
10:36:38 [INFO] Created temp directory at pseudoaligner_tmp
10:36:38 [INFO] Building index from fasta
Segmentation fault (core dumped)
```

The command I'm using is:
`./sc_hla_count_linux --bam outs/possorted_genome_bam.bam --cell-barcodes outs/filtered_feature_bc_matrix/barcodes.tsv.gz -d db -o results
`

The HPC is running Scientific Linux 7.9. I've tried increasing the memory to 120GB, and everything else seems to be in order, but still the error persists. Would you have any ideas as to what might be causing this error?

Thanks!
Sam

**Comment by slukowski** [comment]
Also, since it is crashing at the index step, I tried it with and without a pre-indexed fasta, but no change

**Comment by ErikaZ95** [comment]
Hi. Did you solve the issue? I am having the same problem

**Comment by amoyguang1** [comment]
ok. i figured it out. For me, by change the directionary of ref folder from its name to full path works.

**Comment by amoyguang1** [comment]
also, pay attention to the downloaded files, the size of the 2 fasta files should be 30-80MB. Use the link directly from the file name is wrong, use the link from download button.

**Comment by cdarby** [comment]
@amoyguang1 Thank you for your comment! Is there an incorrect link or instructions in our repo? Please let me know so I can correct it for future users.

**Comment by cdarby** [comment]
@ErikaZ95 Could you try the solution from amoyguang1? If this doesn't resolve your crash, please feel free to open another issue with your specific error and situation.
Best wishes,
Charlotte
