### ISSUE TITLE
using scHLAcount for mouse MHC typing

### ISSUE THREAD

**Issue by liuyanxys** [10XGenomics/scHLAcount#24]
I really like your tool, and I was wondering if it could potentially be applied to infer MHC types in mouse as well. 

Thank you very much in advance!

**Comment by cdarby** [comment]
Hi Liuyanxys! Thanks for your suggestion. We don't have that feature in our development plans, but in theory the same strategy could be applied. If you or your colleagues have implemented the feature, we'd love to consider a pull request.
Best wishes,
Charlotte
