### ISSUE TITLE
using scHLAcount for bulk RNA-seq

### ISSUE THREAD

**Issue by Puputnik** [10XGenomics/scHLAcount#7]
Hi!

I really like the way your tool works, and I was wondering if it was possible to use somehow your tool with bulk RNA-seq data (aligned with STAR) for HLA allele specific expression estimation.

thank you very much in advance!

**Comment by cdarby** [comment]
scHLAcount leverages cell and molecule level information specific to single-cell data. We suggest you try out other tools available in the literature
AltHapAlignR 
https://github.com/jknightlab/AltHapAlignR
HLApers
https://github.com/genevol-usp/HLApers
which are both designed for bulk RNA-seq data.
